---
jobs:
- name: create-Staging-Prod-Pipeline
  plan:
  - aggregate:
    - get: inceptor-repo
      trigger: true
    - get: template-repo
      trigger: true
  - task: build-pipeline-yml-task
    config:
      platform: linux
      image: docker:///silval/ubuntu-bosh-spruce-cf-fly
      inputs:
        - name: inceptor-repo
        - name: template-repo
      run:
        path: inceptor-repo/ci/tools/build_pipeline_yml.sh
        args:
          - template-repo/ci/stubs/pipeline/staging_prod_pipeline.yml
      outputs:
        - name: pipeline

  - task: deploy-pipeline-yml-task
    config:
      platform: linux
      image: docker:///silval/ubuntu-bosh-spruce-cf-fly
      inputs:
        - name: inceptor-repo
        - name: template-repo
        - name: pipeline
      run:
        path: inceptor-repo/ci/tools/update_pipeline.sh
        args:
          - http://192.168.100.4:8080
          - admin
          - admin
          - Staging-Production
          - template-repo/ci/stubs/pipeline/staging_prod_pipeline_creds.yml

resources:
- name: inceptor-repo
  type: git
  source:
    uri: https://github.com/lsilvapvt/concourse-pipeline-inceptor
    branch: master
- name: template-repo
  type: git
  source:
    uri: https://github.com/lsilvapvt/concourse-pipeline-inceptor-templates
    branch: master
#    private_key: { { github-private-key } }
