---
jobs:
- name: create-Sandbox-Dev-pipeline
  plan:
  - aggregate:
    - get: inceptor-repo
      trigger: true
    - get: template-repo
      trigger: true
  - task: create-Sandbox-Dev-Pipeline-task
    config:
      platform: linux
      image: docker:///silval/ubuntu-bosh-spruce-cf-fly
      inputs:
        - name: inceptor-repo
        - name: template-repo
      run:
        path: inceptor-repo/ci/tools/inception.sh
        args:
          - template-repo/ci/stubs/pipeline/sandbox_dev_pipeline.yml
          - http://192.168.100.4:8080
          - admin
          - admin
          - Sandbox-Dev
      outputs:
        - name: pipeline

- name: create-Staging-Prod-Pipeline
  plan:
  - aggregate:
    - get: inceptor-repo
      trigger: true
    - get: template-repo
      trigger: true
  - task: create-Staging-Prod-Pipeline-task
    config:
      platform: linux
      image: docker:///silval/ubuntu-bosh-spruce-cf-fly
      inputs:
        - name: inceptor-repo
        - name: template-repo
      run:
        path: inceptor-repo/ci/tools/inception.sh
        args:
          - template-repo/ci/stubs/pipeline/staging_prod_pipeline.yml
          - http://192.168.100.4:8080
          - admin
          - admin
          - Staging-Production
      outputs:
        - name: pipeline

- name: create-TryAnything-Staging-Prod-Pipeline
  plan:
  - aggregate:
    - get: inceptor-repo
      trigger: true
  - aggregate:
    - get: template-repo
      trigger: true
  - task: create-TryAnything-Staging-Prod-Pipeline-task
    config:
      platform: linux
      image: docker:///silval/ubuntu-bosh-spruce-cf-fly
      inputs:
        - name: inceptor-repo
        - name: template-repo
      run:
        path: inceptor-repo/ci/tools/inception.sh
        args:
          - template-repo/ci/stubs/pipeline/try_staging_prod_pipeline.yml
          - http://192.168.100.4:8080
          - admin
          - admin
          - TryAnything-Staging-Production
      outputs:
        - name: pipeline

resources:
- name: inceptor-repo
  type: git
  source:
    uri: https://github.com/lsilvapvt/concourse-pipeline-inceptor
    branch: master
- name: template-repo
  type: git
  source:
    uri: https://github.com/lsilvapvt/concourse-pipeline-inceptor-templates
    branch: master
#    private_key: { { github-private-key } }
